What is a tensor?
 It’s a multi-dimensional array—essentially a "super-powered" NumPy array that can run on GPUs for massive speed.

The Core: Tensors are the fundamental data structure in PyTorch, acting as the universal language for all AI models.

How to create them?

You can build them from Python lists, NumPy arrays, or specific values using torch.tensor().

Built-in shortcuts

You can also generate them instantly using functions like torch.rand(), torch.ones(), or torch.zeros().

CREATING TENSORS

In [ ]:
import torch
import numpy as np

#Creating tensor of zeros
zeros_tensor = torch.zeros(3,5)
print(f"Zeros tensor\n{zeros_tensor}\n")

#Creating a random tensor
torch.manual_seed(42)
random_tensor = torch.rand(2,5)
print(f"Random tensor\n{random_tensor}\n")

#Creating tensor from a python List
list_tensor = torch.tensor([1,2,3,4,5,6])
print(f"Tensor from list\n{list_tensor}\n")

#Creating a tensor of ones
ones_tensor = torch.ones(3,5)
print(f"Ones tensor\n{list_tensor}")

Zeros tensor
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

Random tensor
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332]])

Tensor from list
tensor([1, 2, 3, 4, 5, 6])

Ones tensor
tensor([1, 2, 3, 4, 5, 6])


Tensor Attributes

.shape: The dimensions of your data

.dtype: The data format (e.g., float32, int64); determines math compatibility and memory use.

.device: The hardware location (cpu or cuda); tensors must be on the same device to work together.


In [14]:
# Create a tensor and inspect its attributes
example_tensor = torch.rand(3, 4, 5)

print("Tensor shape:", example_tensor.shape)
print("Tensor dtype:", example_tensor.dtype)
print("Tensor device:", example_tensor.device)
print("\nFull tensor:\n", example_tensor)

Tensor shape: torch.Size([3, 4, 5])
Tensor dtype: torch.float32
Tensor device: cpu

Full tensor:
 tensor([[[0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
         [0.2695, 0.3588, 0.1994, 0.5472, 0.0062]],

        [[0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
         [0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890],
         [0.2814, 0.7886, 0.5895, 0.7539, 0.1952]],

        [[0.0050, 0.3068, 0.1165, 0.9103, 0.6440],
         [0.7071, 0.6581, 0.4913, 0.8913, 0.1447],
         [0.5315, 0.1587, 0.6542, 0.3278, 0.6532],
         [0.3958, 0.9147, 0.2036, 0.2018, 0.2018]]])
